# Generated by Django 4.0.5 on 2022-07-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
                ('register_date', models.DateTimeField(help_text='登録日')),
                ('icon_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
